### PR TITLE
Implement FocusNotifier and BlurNotifier on AbstractNumberField 

### PR DESCRIPTION
**Pull request by canthony**
AbstractNumberField : implement FieldEvents.FocusNotifier  and FieldEvents.BlurNotifier, along with supporting fluid methods

### CODE REVIEW

**Comment by mstahv** [comment]
Awesome, thanks!

Sorry for taking so long to pull this in, I have been bit overloaded for the beginning of the year due to V8...

**Comment by canthony** [comment]
@mstahv No worries: I am similarly overloaded elsewhere, and am not able to look at V8 yet. Looking forward to it, though. A *little* concerned at a comment I skimmed elsewhere that Viritin & V8 were not happy bedfellows. Is that FUD?

**Comment by mstahv** [comment]
Where was that comment? It will be, I just haven't found time for the upgrade yet. Some improvements in Vaadin 8 make some Viritin features obsolete, but there is still a massive amounts of improvements that I need for my hobby projects at least.

**Comment by canthony** [comment]
Ah: it was in the comments on the vaadin.com blog post https://vaadin.com/blog/-/blogs/vaadin-framework-8-is-out - but you've already responded. I must have read it in the 4 hours between the OP posting, and responding. 4hrs? Come on Matti, why so slow - surely you have nothing else on your plate ;)

**Comment by mstahv** [comment]
I guess I need to start drinking coffee again to gain some hours more for the day :-)

**Pull request merged**
