### PR TITLE
Fixed NPE on SortableLazyList.findEntities (fixes #249).

### LINKED ISSUE #249: NPE in SortableLazyList when no sort properties are given
SortableLazyList.findEntities throws a NPE when initialized without sort properties.
NPE comes from getting first element of sort properties array that could be null (getSortProperty()[0]) 

```java
    protected List<T> findEntities(int i) {
        if(multiSortablePageProvider != null) {
            return multiSortablePageProvider.findEntities(i, getSortAscending(), getSortProperty());
        }
        return sortablePageProvider.findEntities(i, isSortAscending(), getSortProperty()[0]);
    }
```

To reproduce lauch UI test `AspectAttributeTest.testLanguageByBrowser`; it will show error in browser window (and STDOUT of course).

### PR DESCRIPTION
**Pull request by mcollovati**
Added check for null sortProperty before invoking sortablePageProvider

### CODE REVIEW

**Comment by mstahv** [comment]
Oh, just when to close the issue in separate changeset :-)

I'll merge your change anyways to get the change in....

**Comment by mcollovati** [comment]
I'm sorry. I saw your comment on the issue pointing to my commit so I created the pull request :)

**Comment by mstahv** [comment]
Yep, wrong reference, didn't remember to push mine, just picked the last one from timeline :-)

NP, good to do some git exercises, almost as tricky as playing sudoku :-)

**Comment by mstahv** [comment]
Thanks for the test case, those are super valuable!

**Comment by mstahv** [comment]
Do you think we'd be ready for a release? I think I'll do some manual testing still and then build it. There are lots of unused version numbers, we'll build an new one tomorrow if there are critical issue.

**Pull request merged**
