### PR TITLE
fix felix osgi settings (embed markdown4j), now starts up in karaf

### PR DESCRIPTION
**Pull request by datenhahn**
Tested with karaf 4.0.4 fresh install.

untar and execute bin/karaf.

First load all dependencys (they are not in the correct order, just execute all commands, then do bundle:list and bundle:start  + the ID of the two bundles who did not start before).

install -s mvn:org.vaadin.addon/confirmdialog/2.1.3
install -s mvn:org.apache.commons/commons-lang3/3.4
install -s mvn:commons-io/commons-io/2.4
install -s mvn:commons-collections/commons-collections/3.2.2
install -s mvn:commons-beanutils/commons-beanutils/1.9.2
install -s mvn:javax.validation/validation-api/1.1.0.Final
install -s mvn:com.vaadin.external.flute/flute/1.3.0.gg2
install -s mvn:com.vaadin.external.streamhtmlparser/streamhtmlparser-jsilver/0.0.10.vaadin1
install -s mvn:com.vaadin/vaadin-shared/7.6.2
install -s mvn:com.vaadin.external.google/guava/16.0.1.vaadin1
install -s mvn:org.jsoup/jsoup/1.8.3
install -s mvn:javax.servlet/javax.servlet-api/3.1.0
install -s mvn:com.vaadin/vaadin-server/7.6.2

Then start the viritin bundle:
install -s mvn:org.vaadin/viritin/1.45-SNAPSHOT

### CODE REVIEW

**Comment by mstahv** [comment]
@florianpirchner & @mamtabansal, can you give your input on this change as well?

So the jar file gets embedded in jar file and OSGi environments can pick it up automatically, other environments just ignore it and work as they did before?

Looks pretty decent workaround for me as I think quite rare (OSGi) people have a special need to override the version of this specific dependency. But as said, I have no real world OSGi experience, so I'm just guessing... I need to do some OSGi app at some point to get some basic skills.

**Comment by florianpirchner** [comment]
Hey,

embedding the dependency is fine!

As mentioned in the other ticket, we have created a pull request for OSGi-ifying the markdown4j bundle. It was accepted but is not available at maven central for now.

I would use the following pom.

```
<instructions>
	<Embed-Dependency>markdown4j;scope=compile|runtime</Embed-Dependency>
	<Export-Package>org.vaadin.viritin.*</Export-Package>
	<Import-Package>
		*,
		org.markdown4j;resolution:=optional
	</Import-Package>
</instructions>
```

- Embedd-Dependency makes the jar file part of the "bundles-class path".
- Import-Package org.markdown4j;resolution:=optional tells the OSGi-classloader to look for an different bundle which exports the package org.markdown4j. If no bundle could be found, then the bundle will load the markdown4j classes from its own classspace.

See this blog about the OSGi-Classloader:
https://floriansblog.wordpress.com/2015/06/18/osgi-and-vaadin-using-classresource/

With the pom above i did some tests, and it worked fine.

Best
Florian

**Comment by mstahv** [comment]
Excellent, thanks Flo for the complete explanation. @datenhahn wan't to enhance the pull request a bit with the suggestions from @florianpirchner?

I also teased the markdown4j developer a bit to publish an fixed version to central. I guess that would be the best solution for everybody.

**Comment by datenhahn** [comment]
I switched the order of the import list as if I interpret it correctly any exception to the "all" star-import has to be listed before it.

http://felix.apache.org/documentation/subprojects/apache-felix-maven-bundle-plugin-bnd.html

The package patterns work in the same way as for <Export-Package>, which means they are ordered. For example, if you wanted to import all packages except org.foo.impl you would specify "!org.foo.impl,*"

@florianpirchner can you confirm that, or does it work differently

**Comment by florianpirchner** [comment]
@datenhahn you are right. The docu states that they are ordered.

I did two tests with different orders. Both resulted in the same proper import packages.

But yep! We should follow the guidlines of "maven-bundle-plugin".

Best, Flo

**Comment by mstahv** [comment]
Excellent dudes, I'll build a new version soon.

**Comment by mstahv** [comment]
And now the osgi compatible version is in central :-) I guess it is best now just to build a version against that and leave out the embedding.

**Comment by datenhahn** [comment]
Where can I find it? I will test then without the embedded dependency

**Comment by datenhahn** [comment]
nevermind, I searched on http://mvnrepository.com, but in central it is already available as you said

**Pull request merged**
