### PR TITLE
Extracted loacle negotiantion strategy

### PR DESCRIPTION
**Pull request by dve**
I hope this is a ok approach for java 7/8 issues? Compile with java 8 and then uses it in java 7 anyway?

### CODE REVIEW

**Comment by mstahv** [comment]
Hi, the bad thing here is that it don't compile properly ;-) I typically have projects compiled with the target JDK to avoid this kind of issues in first place and NetBeans actually does this automatically for me if pom.xml has java 7.

I have couple possible solutions we should look into:
 * Try to use the jdk 8 API with reflection and if the new API isn't there, fallback to the workaround
 * Check what the jdk8 method really does and check out if similar can be easily implemented with jdk7
 * look for a jdk 7 compatible library that does the same and depend on that, there must be one.

**Comment by dve** [comment]
Hi,
than i would suggest we first remove the java 8 implementation of the strategy. When I have some time I will take a look what it does internally and provide a patch either with the reflection idea or a copy and paste implementation. My feeling is that we should not add an extra dependency for something which is implemented in the current jdk. And my first impression was that locale negotiation is something which is not broke out to a separate library.

**Comment by dve** [comment]
I use reflection now to do the java 1.8 stuff, so it should compile with jdk 1.7

**Comment by mstahv** [comment]
Perfect, builds well now with Java 7 as well. Thanks!

**Pull request merged**
