### PR TITLE
Update MTable.java

### PR DESCRIPTION
**Pull request by cbmeeks**
Added custom "withFullExpansion" method that sets full width and full height.  Plus, it will scan the list of property ID's and automatically scan the first one it finds.  Useful for tables with a default "name" column on the left and value columns on the right.

### CODE REVIEW

**Comment by mstahv** [comment]
Hi,

I'd consider expandFirstColumn as a method name, how does that sound to you?

An alternative approach would be to add a special handy for 0 length var args in expand method. Then the same thing could be configured with:

    .expand().withFullWidth()

cheers,
matti

**Comment by mstahv** [comment]
The pro of that would be to avoid calling withFullWidth that might be odd if somebody has defined an explicit width.

**Comment by cbmeeks** [comment]
I think 
    .expandFirstColumn()
sounds like a great idea.



.

**Comment by mstahv** [comment]
I have the the project open, I'll pull this in and rename it.

**Pull request merged**
