### PR TITLE
TypedSelect with individual configuration - usage example

### PR DESCRIPTION
**Pull request by melistik**
As wished here an usage example as a test.

Further more I found a bug, but don't know how to solve this issue.
TwinColSelect doesn't trigger MValueChangeListener when perform setValue on TypedSelect!

This has nothing to do with my changes...
Maybe you have a clue ;)

### CODE REVIEW

**Comment by mstahv** [comment]
Can you create a separate issue about the bug?

**Comment by melistik** [comment]
Ok - when you make a release ;)

**Comment by mstahv** [comment]
I shortly looked into this. Just noticed that the issue is with TwinColSelect, which is by default multiselect -> not compatible with TypedSelect. I bet the problem is also because of this.

I don't see it ever being good decision to use TwinColSelect for single selection, so maybe that should completely be removed from TypedSelect. There could be similar multiselect component, bit like MultiSelectTable but built on to of TwinColSelect.

**Comment by mstahv** [comment]
Created issue #197 about this.

**Comment by mstahv** [comment]
I fixed #197 and cut a release. Big thanks to your efforts, this was mostly your release 👍

**Pull request merged**
